"""
To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.

Input Specification:

Each input file contains one test case. Each case contains a positive integer N (≤1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.

Output Specification:

For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line There are N accounts and no account is modified where N is the total number of accounts. However, if N is one, you must print There is 1 account and no account is modified instead.

Sample Input 1:

3
Team000002 Rlsp0dfa
Team000003 perfectpwd
Team000001 R1spOdfa
Sample Output 1:

2
Team000002 RLsp%dfa
Team000001 R@spodfa
Sample Input 2:

1
team110 abcdefg332
Sample Output 2:

There is 1 account and no account is modified
Sample Input 3:

2
team110 abcdefg222
team220 abcdefg333
Sample Output 3:

There are 2 accounts and no account is modified
"""


#########################################
"""
本题非常简单，竟然不是一次通过。。。改变赋值时多输了一个=号。。。在验证时没看仔细！
"""
#########################################


n = int(input())
change, record = 0, []
for _ in range(n):
    account, password = input().split()
    password = list(password)
    changed = False
    for i in range(len(password)):
        if password[i] == '1':
            password[i] = '@'
            changed = True
        elif password[i] == '0':
            password[i] = '%'
            changed = True
        elif password[i] == 'l':
            password[i] = 'L'
            changed = True
        elif password[i] == 'O':
            password[i] = 'o'
            changed = True
    if changed:
        change += 1
        record.append([account, ''.join(password)])
if change != 0:
    print(change)
    for i in record:
        print(i[0], i[1])
else:
    if n == 1:
        print("There is 1 account and no account is modified")
    else:
        print("There are %d accounts and no account is modified" % n)
